platform :ios, '8.0'
use_frameworks!

target 'RemixerExample' do
  pod 'Remixer', :path => '../../'

  target 'RemixerExampleTests' do
    pod 'OCMock'
  end

  target 'RemixerExampleUITests' do
  end
end
